### ISSUE TITLE
Insta

### ISSUE THREAD

**Issue by zZyreXx** [A-d-i-t-h-y-a-n/hermit-md#10]
#1Some insta post/reels not downloading showing "no media found" #2 story command not working plss fix it.

**Comment by A-d-i-t-h-y-a-n** [comment]
> #1Some insta post/reels not downloading showing "no media found" #2 story command not working plss fix it.

Ham,
Some times the Instagram downloader site does not work properly,
Because of the new Instagram security updates (in instagram.com website not in the app)

you can also Sponsor a good scraper for instagram (if you a dev)

**Comment by zZyreXx** [comment]
Kk, I will let you know

**Comment by A-d-i-t-h-y-a-n** [comment]
> #1Some insta post/reels not downloading showing "no media found" #2 story command not working plss fix it.

Ham, about the story downloader,

Only some of site does work for downloading story,
Almost of the site are protected by reCAPTCHA,

Only 1-2 site are not protected,
Me and my team are working on it to scrape those site..
