### ISSUE TITLE
Unknown Device

### ISSUE THREAD

**Issue by Huguitis** [A-d-i-t-h-y-a-n/hermit-md#135]
![imagen](https://github.com/A-d-i-t-h-y-a-n/hermit-md/assets/65133800/7c757ac3-88d9-4d39-bece-35ec9485d34d)
It shows this but I'm using the official app!

**Comment by A-d-i-t-h-y-a-n** [comment]
👎

**Comment by Huguitis** [comment]
Uh? Why did you close my issue? You can at least tell me how to fix it...
