### ISSUE TITLE
Error Koyeb

### ISSUE THREAD

**Issue by Huguitis** [A-d-i-t-h-y-a-n/hermit-md#136]
![imagen](https://github.com/A-d-i-t-h-y-a-n/hermit-md/assets/65133800/5517ca9a-8e5a-41ac-a3cc-37f941e3b9f9)
![imagen](https://github.com/A-d-i-t-h-y-a-n/hermit-md/assets/65133800/b5a57f2f-6b68-4ba7-9257-1a92fc986811)

**Comment by ADK-RICHU** [comment]
Same issue
