### ISSUE TITLE
MENTION 

### ISSUE THREAD

**Issue by ADK-RICHU** [A-d-i-t-h-y-a-n/hermit-md#170]
Koyebil deploy cheyyumbol audio mention work aakunnilla 😕

**Comment by A-d-i-t-h-y-a-n** [comment]
Koyeb doesn't support imgur url

**Comment by ADK-RICHU** [comment]
> Koyeb doesn't support imgur url

Thankzz broh 🫂❤‍🩹

**Comment by ADK-RICHU** [comment]
> Koyeb doesn't support imgur url

Imgur url allathe Vere link engane kittum 👀 ath koode onnu paranj tharavo
