### ISSUE TITLE
INVALID SESSION_ID, SCAN AGAIN!! Notice

### ISSUE THREAD

**Issue by boiyelove** [A-d-i-t-h-y-a-n/hermit-md#178]
After running docer build anf run, I get the error invalid session id scan again.
I need to know how to run this repo locally.

How so I access the container: localhost:port to see the scan url
![image](https://github.com/A-d-i-t-h-y-a-n/hermit-md/assets/4135713/dc7bf202-1e95-4425-8e85-2d6d8987e100)

**Comment by A-d-i-t-h-y-a-n** [comment]
The session id is only vaild in server for 24hour

**Comment by boiyelove** [comment]
I think you misunderstand. I am unable to setup a session at all on my local machine.
How does one setup a session after pulling the code from github?

**Comment by A-d-i-t-h-y-a-n** [comment]
what pulling?
