### ISSUE TITLE
QR ISSUE 

### ISSUE THREAD

**Issue by RichieMonet** [A-d-i-t-h-y-a-n/hermit-md#188]
What’s wrong with the qr link it’s talking us back to google pls work on it

**Comment by RichieMonet** [comment]
Are you going to do anything about this @A-d-i-t-h-y-a-n or you will just closed the issue without any solution or reply 😬😬😬😬

**Comment by Riders004** [comment]
He can't Reply here just message him in WhatsApp

**Comment by RichieMonet** [comment]
> He can't Reply here just message him in WhatsApp

His WhatsApp number pls 🙏🙏

**Comment by Riders004** [comment]
Check bio of her profile
