### ISSUE TITLE
Regarding antilink

### ISSUE THREAD

**Issue by Guru322** [A-d-i-t-h-y-a-n/hermit-md#36]
How can we add more allowed websites to the antilink system

**Comment by A-d-i-t-h-y-a-n** [comment]
Hem,
it's very simple,
Example: 
.antilink link,link,link......

i use this in hermit support group

,antilink LOMGBEO2i9vKew562o1LFk,gist.github.com,you,tiny,heroku,imgur

**Comment by Guru322** [comment]
Thanks
