### ISSUE TITLE
Koyeb error when starting bot

### ISSUE THREAD

**Issue by NatsuoKakashi** [A-d-i-t-h-y-a-n/hermit-md#85]
[PM2][INFO] Log streaming apps id: 0, exit with Ctrl-C or will exit in 10secs
0|hermit-md | hermit-md v4.3.2
0|hermit-md | App listening on port 3000
0|hermit-md | HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND dpg-ced517un6mpgskjf6b0g-a
0|hermit-md | at Client._connectionCallback (/root/hermit-md/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)
0|hermit-md | at Client._handleErrorWhileConnecting (/root/hermit-md/node_modules/pg/lib/client.js:305:19)
0|hermit-md | at Client._handleErrorEvent (/root/hermit-md/node_modules/pg/lib/client.js:315:19)
0|hermit-md | at Connection.emit (node:events:527:28)
0|hermit-md | at Socket.reportStreamError (/root/hermit-md/node_modules/pg/lib/connection.js:52:12)
0|hermit-md | at Socket.emit (node:events:527:28)
0|hermit-md | at emitErrorNT (node:internal/streams/destroy:157:8)
0|hermit-md | at emitErrorCloseNT (node:internal/streams/destroy:122:3)
0|hermit-md | at processTicksAndRejections (node:internal/process/task_queues:83:21) {
0|hermit-md | parent: Error: getaddrinfo ENOTFOUND dpg-ced517un6mpgskjf6b0g-a
0|hermit-md | at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
0|hermit-md | errno: -3008,
0|hermit-md | code: 'ENOTFOUND',
0|hermit-md | syscall: 'getaddrinfo',
0|hermit-md | hostname: 'dpg-ced517un6mpgskjf6b0g-a'
0|hermit-md | },
0|hermit-md | original: Error: getaddrinfo ENOTFOUND dpg-ced517un6mpgskjf6b0g-a
0|hermit-md | at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
0|hermit-md | errno: -3008,
0|hermit-md | code: 'ENOTFOUND',
0|hermit-md | syscall: 'getaddrinfo',
0|hermit-md | hostname: 'dpg-ced517un6mpgskjf6b0g-a'
0|hermit-md | }
0|hermit-md | }
npm notice
npm notice New minor version of npm available! 9.2.0 -> 9.3.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.3.1>
npm notice Run `npm install -g npm@9.3.1` to update!
npm notice
npm ERR! path /root/hermit-md
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c pm2 start . --attach --name hermit-md
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2023-01-20T11_34_14_984Z-debug-0.log

**Comment by A-d-i-t-h-y-a-n** [comment]
Your database url problem, 
try render database url
